# Версия конфигурации
version: "1.0"

# Настройки сборки
build_settings:
  # Тип устройства
  - id: device_type
    label: "Device Type"
    value: "type"
    define: DEVICE_TYPE
    description: "Device type number (4-32). Each number represents a specific hardware variant."
    field_type: range
    format: number
    validation:
      min: 4
      max: 32

  # Режим работы устройства
  - id: device_mode
    label: "Device Mode"
    value: "mode"
    description: "Operating mode that determines device behavior and available features"
    field_type: select
    format: string
    options:
      - label: "MDB Gateway"
        value: "MDB"
        define: "DEVICE_MODE_MDB_GATEWAY"
        description: "MDB Protocol gateway mode for vending machines"
      
      - label: "Micromarket"
        value: "MICROMARKET"
        define: "DEVICE_MODE_MICROMARKET"
        description: "Automated retail point of sale mode"
      
      - label: "Retail"
        value: "RETAIL"
        define: "DEVICE_MODE_RETAIL"
        description: "Standard retail payment terminal mode"
      
      - label: "Transport Ticket Validator"
        value: "TT_VALID"
        define: "DEVICE_MODE_TRANSPORT_TICKET_VALIDATOR"
        description: "Public transport ticket validation mode"
      
      - label: "AZS"
        value: "AZS"
        define: "DEVICE_MODE_AZS"
        description: "Gas station payment terminal mode"
      
      - label: "Gashapon"
        value: "GASH"
        define: "DEVICE_MODE_GASHAPON"
        description: "Vending machine mode for capsule toys"
      
      - label: "VRelay"
        value: "VREL"
        define: "DEVICE_MODE_VRELAY"
        description: "Virtual relay control mode"

  # Поддерживаемые языки
  - id: languages
    label: "Languages"
    value: "lang"
    description: "Supported interface languages. At least one language must be selected."
    field_type: checkbox_group
    format: string[]
    min_selected: 1
    options:
      - label: "English"
        value: "en"
        define: "LANG_EN"
        description: "English language support"
      
      - label: "Russian"
        value: "ru"
        define: "LANG_RU"
        description: "Russian language support"
      
      - label: "Kazakh"
        value: "kz"
        define: "LANG_KZ"
        description: "Kazakh language support"

  # Дополнительные опции
  - id: additional_options
    label: "Additional Options"
    value: "opt"
    description: "Optional features and payment systems that can be enabled"
    field_type: checkbox_group
    format: string[]
    options:
      - label: "BelCard Support"
        value: "BelCard"
        define: "ENABLE_BELCARD"
        description: "Enable support for BelCard payment system"
      
      - label: "Kaspi QR Support"
        value: "KSP_QR"
        define: "ENABLE_KASPI_QR"
        description: "Enable support for Kaspi QR payments"
